### ISSUE TITLE
Ctrl-C quickly after command causes radssh to quit

### ISSUE THREAD

**Issue by mckellyln** [radssh/radssh#45]
Thanks for awesome raddsh.  Once in a while if I Ctrl-C quickly after I issue a command I get booted out of radssh:
```
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/radssh/shell.py", line 458, in <module>
    radssh_shell_main()
  File "/usr/local/lib/python2.7/dist-packages/radssh/shell.py", line 454, in radssh_shell_main
    shell(cluster=cluster, logdir=logdir, defaults=defaults)
  File "/usr/local/lib/python2.7/dist-packages/radssh/shell.py", line 120, in shell
    r = cluster.run_command(cmd)
  File "/usr/local/lib/python2.7/dist-packages/radssh/ssh.py", line 774, in run_command
    self.pending[self.dispatcher.submit(exec_command, k, t, cmd, self.quota, None, self.defaults['character_encoding'])] = k
  File "/usr/local/lib/python2.7/dist-packages/radssh/dispatcher.py", line 120, in submit
    self.inQ.put((job_id, handler, args, kwargs))
  File "/usr/lib/python2.7/Queue.py", line 118, in put
    self.not_full.acquire()
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 78, in _join_lingering_threads
    thr.stop_thread()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1551, in stop_thread
    self.join(10)
  File "/usr/lib/python2.7/threading.py", line 951, in join
    self.__block.wait(delay)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
```

**Comment by mckellyln** [comment]
Here is another traceback:
```
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/radssh/shell.py", line 458, in <module>
    radssh_shell_main()
  File "/usr/local/lib/python2.7/dist-packages/radssh/shell.py", line 454, in radssh_shell_main
    shell(cluster=cluster, logdir=logdir, defaults=defaults)
  File "/usr/local/lib/python2.7/dist-packages/radssh/shell.py", line 122, in shell
    cluster.log_result(logdir, encoding=defaults['character_encoding'])
  File "/usr/local/lib/python2.7/dist-packages/radssh/ssh.py", line 838, in log_result
    f.write(("[{0}]".format(str(k)) + filter_tty_attrs(line).decode(encoding, 'replace') + "\n").encode(encoding))
  File "/usr/local/lib/python2.7/dist-packages/netaddr/ip/__init__.py", line 657, in __str__
    return self._module.int_to_str(self._value)
  File "/usr/local/lib/python2.7/dist-packages/netaddr/strategy/ipv4.py", line 141, in int_to_str
    if 0 <= int_val <= max_int:
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 78, in _join_lingering_threads
    thr.stop_thread()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1551, in stop_thread
    self.join(10)
  File "/usr/lib/python2.7/threading.py", line 951, in join
    self.__block.wait(delay)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
```
