### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'linux_distribution'

### ISSUE THREAD

**Issue by netmet1** [radssh/radssh#48]
### Python 3.7 or 3.8 package removal

I'm receiving the following error while following instructions on the `verify the install` section of the [radssh readthedocs](https://radssh.readthedocs.io/en/v1.1.0/installation.html#installing-from-pypi)

output

```
/ # python -m radssh.__main__
RadSSH Main Module
Package RadSSH 1.1.0 from (/usr/local/lib/python3.8/site-packages/radssh/__init__.py)        
  Using Paramiko  2.7.1 from /usr/local/lib/python3.8/site-packages/paramiko/__init__.py     
  Using cryptography 2.9 from /usr/local/lib/python3.8/site-packages/cryptography/__init__.py
  Using netaddr 0.7.19 from /usr/local/lib/python3.8/site-packages/netaddr/__init__.py       

Python 3.8.1 (CPython)
Running on Linux [7ceff6209afb]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/radssh/__main__.py", line 82, in <module>
    print('  %s (%s)' % (platform.linux_distribution()[0],
AttributeError: module 'platform' has no attribute 'linux_distribution'
```
Thank you!

**Comment by mckellyln** [comment]
Does platform.dist() work instead ?
```
if platform.system() == 'Linux':
    print('  %s (%s)' % (platform.dist()[0],
                             '/'.join(platform.dist()[1:])))
```

**Comment by eorochena** [comment]
The functionality has been removed on Python3.8 [https://docs.python.org/2/library/platform.html](platform)

**Comment by mckellyln** [comment]
Hi,
Yes, change it to dist() as shown above :-)

**Comment by eorochena** [comment]
I'm submitting a PR for this

**Comment by mckellyln** [comment]
ok, cool.  I also updated it in my radssh PR of many other things, including your other PR.

**Comment by eorochena** [comment]
PR https://github.com/radssh/radssh/pull/47 has been update to include this fix as well.

**Comment by radssh** [comment]
Considering the distro package - I'm a bit disappointed that it's not part of the standard library any more, and this change adds another dependency . It's not huge, but the runtime info report is the only place that makes/made use of platform.linux_distribution, so I was considering reducing the detail to only what current platform module can provide.
