### ISSUE TITLE
KeyError: 'auto_tty' when connecting to a single host

### ISSUE THREAD

**Issue by eorochena** [radssh/radssh#56]
When trying to connect to a single host using radssh, I'm getting the following error message.

> % python3.8 -m radssh.shell --username=eorochena 192.168.1.130
Connecting to 1 hosts...
.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/eorochena/github/radssh/radssh/shell.py", line 516, in <module>
    radssh_shell_main()
  File "/Users/eorochena/github/radssh/radssh/shell.py", line 486, in radssh_shell_main
    if defaults['auto_tty'] == 'on' and 'star_tty' in loaded_plugins:
KeyError: 'auto_tty'

**Comment by eorochena** [comment]
Proposed [fix](https://github.com/radssh/radssh/pull/54 )  I'm leaving the default as auto_tty=on, @mckellyln  
@radssh please take a look and let me know if this works out.

**Comment by mckellyln** [comment]
@eorochena yes, I agree.  I have auto_tty=on in my radssh_config file but it should also be in the base config.
