### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by Eli-Tarrago** [radssh/radssh#58]
Python 3.8.5
Radssh 1.1.3

Following steps:
 `virtualenv radssh`
`cd radssh; source bin/activate`
`git clone git@github.com:radssh/radssh.git`
`python setup.py install`

```
Merging plugins from radssh/core_plugins
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    shutil.copy2(os.path.join(p, plugin), 'radssh/plugins')
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'radssh/plugins/ssh_key.py'
```

Fix:
`sudo chown -R user:group .`

Cause:
```
ls -al ~/radssh/radssh/radssh/plugins
-rw-r--r--   1 root    staff  7414 Oct 27 11:54 __init__.py
-rw-r--r--   1 root    staff  3142 Oct 27 11:54 __main__.py
-rw-r--r--   1 root    staff  2432 Oct 27 11:54 add_drop.py
-rw-r--r--   1 root    staff  3118 Oct 27 11:54 alias.py
-rw-r--r--   1 root    staff   740 Oct 27 11:54 auth.py
-rw-r--r--   1 root    staff  2146 Oct 27 11:54 banner.py
-rw-r--r--   1 root    staff  1195 Oct 27 11:54 file_lookup.py
-rw-r--r--   1 root    staff  2632 Oct 27 11:54 formatters.py
```

Improper permissions on the plugins dir? Doesn't git automatically chown all files to local user?

**Comment by mckellyln** [comment]
Is that you ?  How are you ?

**Comment by Eli-Tarrago** [comment]
It's me. I think about you guys all the time. Great just moved up to WPB with the girly. I would like to reconnect with you guys over coffee and zoom?

**Comment by radssh** [comment]
I walked through the steps you listed, and there seems to be a missing `cd` in there, after the git clone step. The current directory after that clone does not have the setup.py script, but cd'ing into the cloned directory was able to successfully install the package into the virtual environment for me.

Confusing to see 3 levels of radish directories in `ls -al ~/radssh/radssh/radssh/plugins`, so I suspect something was leftover from a previous attempt, making the reproduce steps not as clean as they should be.

**Comment by Eli-Tarrago** [comment]
~/radssh/radssh/radssh/

First radssh is the virtualenv folder
Second radssh is the git folder.
Third level is your sauce.
